Fix for issue of gnat2goto crashing when handling a size that isn't a power of 2
diffblue/gnat2goto pull request #259
Opened 2019-06-24 13:47 UTC by NlightNFotis

In investigating the `gnat2goto : Do_Constant / Constant Type not in symbol table / N_Integer_Literal` error reported in another repository, I found myself unable to reproduce the issue discussed there, but I was able to make `gnat2goto` crash when it was loading a type from a gnat file called `interfac.ads` that contained an `unsigned_24` type with `'Size` equal to `24`.

2019-06-24 14:03 UTC, xbauch commented on gnat2goto/driver/tree_walk.adb
> +            pragma Assert (Entity_Esize >= Expression_Value);
Fine by me, but I'm not really sure what would happen if some code depended on the size of a variable being smaller than what is passed on to cbmc.

2019-06-24 14:03 UTC, xbauch approved these changes
Looks good.

2019-07-25 14:27 UTC, martin-cs requested changes
Please can we have a regression test for the specific issue that you are fixing.  Also, this creates quite a substantial change to the golden results; more than I would expect for the issue quoted.  Please can you double check these.

2022-05-24 15:41 UTC, NlightNFotis commented
Going ahead and closing this PR, seeing as there's a lot of conflicting files and not a lot of time to address that from my end.

If for some reason you'd like to see this through, however, feel free to pick up the work from my fork's branch.

2022-05-24 15:41 UTC, closed without merging